### ISSUE TITLE
Data types & operators. Objects and functions / Task 1

### ISSUE THREAD

**Issue by shavlenkov** [illiayatsentyuk/Code#1]
1. Вместо e == null можно было юзать оператор !

До:

```
if(e==null) {
     return this.images[0];
}
```

После:

```
if(!e) {
    return this.images[0];
}
```

2. По хорошему надо создать сеттеры для images
3. Там где reviews было бы прикольно создать прям отдельную функцию-констуктор, как и в Product
4. Функция getAvarageRating нужно было возвращать не среднее значение кажадого параметра (price, service, ...), а среднее всех этих параметров. То есть (price + service + ...) / кол. параметров
5. Метод deleteReview работает неправильно. Тебе надо удалять отзыв по полю айди, а ты удаляешь именно по индексу массива

В этом случае ничего не удалится:

```
const Product1 = new Product('Iphone Xr', 500, 'Apple', 'XL', 10000, "1999-10-5 5:5:5", 'Super phone');


Product1.addReview({
    id: '100',
    author: 'Illia',
    comment: "The best phone ever",
    date: "1999-10-5 5:5:5",
    rating: {
      service: 5,
      price: 3,
      value: 10, 
      quality: 10,
    }
  });
  
  Product1.addReview({
    id: '2',
    author: 'Oleksiy',
    comment: "The best phone ever",
    date: "1999-10-5 5:5:5",
    rating: {
      service: 1,
      price: 3,
      value: 5, 
      quality: 0,
    }
  });
  
  
console.log(Product1.reviews);
Product1.deleteReview(100);
console.log(Product1.reviews);
```

**Comment by illiayatsentyuk** [comment]
Исправил
